version: '3'

networks:
  service_network:
    external: true

services:
  son-catalogue-repos:
    build: .
    image: son-catalogue:SNAPSHOT
    container_name: repository
    networks:
      - service_network
    restart: always

  son-catalogue-repos-doc:
    build: .
    image: son-catalogue-doc:SNAPSHOT
    container_name: repository-doc
    networks:
      - service_network
    command: [rake,yard]
    command: [yard, server, -B, 0.0.0.0]
    restart: always

  mongo:
    image: mongo:3.0.4
    container_name: mongo
    networks:
      - service_network
    command: --smallfiles --rest
    restart: always

  mongoexpress:
    image: mongo-express
    container_name: mongoexpress
    networks:
      - service_network
    restart: always
